[[ACCOUNTS]]
address = "rHxyLo9ygu99xAdq2booG7ZpqQkiE5hwqo"

[[CURRENCIES]]
code = "GRINDX"
issuer = "rs9cwRu1Ce8cgUrs7CQbwp4rPTiVBGTNjR"
display_decimals = 6
description = "GRINDX is a meme token created by DrBonez to fuel the grind."
url = "https://drbonezgrindx.github.io"
icon = "https://raw.githubusercontent.com/DrBonezGrindX/drbonezgrindx.github.io/main/grindx-logo-new.png"
