[[ACCOUNTS]]
address = "rs9cwRu1Ce8cgUrs7CQbwp4rPTiVBGTNjR"

[[CURRENCIES]]
currency = "GRINDX"
issuer = "rs9cwRu1Ce8cgUrs7CQbwp4rPTiVBGTNjR"
display_decimals = 6
desc = "GRINDX is a meme token created by DrBonez to fuel the grind."
url = "https://drbonezgrindx.github.io"
icon = "https://drbonezgrindx.github.io/grindx-logo-new.png"

[[CURRENCIES.resources]]
url = "https://drbonezgrindx.github.io/GRINDX_Onboarding_xGuide.pdf"
description = "GRINDX Onboarding Guide"

[DOCUMENTATION]
org_name = "GRINDX"
org_url = "https://drbonezgrindx.github.io"
